version: '3'
services:
  # Rest API
  sails-api:
    container_name: sails-api
    restart: always
    build: .
    ports:
      - '1337:1337'
    volumes:
      - ./assets/images:/usr/src/app/assets/images
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - sailsapi

  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sailsapi
      MYSQL_USER: sailsapi
      MYSQL_PASSWORD: Ffp496By
    networks:
      - sailsapi

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - sailsapi

networks:
  sailsapi:
volumes:
  db_data:
